juanbalofredo/PF-grupo2

client/src/index.js
client/src/redux/axios.js
client/src/redux/slice.js
client/src/store/store.js

Redux toolkit

---

api/index.js
api/node_modules/.package-lock.json
api/package-lock.json
api/package.json
api/src/config/app.js
api/src/config/db.js
api/src/config/server.js
api/src/routes/post.Coment.js
api/src/routes/products.Router.js
client/src/components/assets/NavBar.jsx

Arme una base para arrancar el back.

Base de back

---

client/src/App.js
client/src/components/assets/NavBar.jsx
client/src/components/assets/User.jsx
client/src/index.js
client/src/views/home/Home.jsx

Configure store

---

api/package.json
api/src/config/app.js
api/src/config/db.js
api/src/controllers/allProducts.js
api/src/helpers/apiInfo.js
api/src/helpers/products.js
api/src/models/market.js
api/src/models/products.js
api/src/routes/post.Coment.js
api/src/routes/products.Router.js

falta verificar dataBase

---

client/src/redux/apiPetitions.js
client/src/views/Card/Card.jsx
client/src/views/Card/card.css
client/src/views/home/Home.jsx
client/src/views/home/home.css

Agregue component card , lo mostre en el home y los agregue al estado global

Productos en el home y Card

---

api/src/config/app.js
api/src/controllers/allProducts.js
api/src/controllers/allUsers.js
api/src/controllers/postUser.js
api/src/controllers/users.js
api/src/helpers/apiInfo.js
api/src/helpers/createUser.js
api/src/helpers/users.js
api/src/models/users.js
api/src/routes/products.Router.js
api/src/routes/user.Router.js

rutas user y products modularizados

---

api/src/config/app.js
api/src/helpers/createUser.js
api/src/models/users.js

cambiado a email y avatar sin image

---

api/src/models/users.js
api/src/routes/user.Router.js

valores por defectos creados

---

api/src/controllers/product.controller.js
api/src/controllers/users.controller.js
api/src/helpers/products.helper.js
api/src/helpers/users.helper.js
api/src/routes/comment.Router.js
api/src/routes/market.Router.js
api/src/routes/post.Coment.js
api/src/routes/products.Router.js
api/src/routes/user.Router.js

edite products.controller , products.helper par agregar la ruta /products/category/:category

agregue la ruta productsByCategory

---

client/src/views/register/Register.jsx

register finalizado

---

api/src/controllers/users.controller.js
api/src/helpers/createUser.helper.js
api/src/helpers/reviews.helper.js
api/src/helpers/users.helper.js
api/src/routes/user.Router.js

delete user terminado aceptar pls

delete user terminado

---

api/src/controllers/reviews.controller.js
api/src/helpers/reviews.helper.js
api/src/routes/review.Router.js

delete reviews terminado

---

api/src/controllers/product.controller.js
api/src/controllers/reviews.controller.js
api/src/controllers/users.controller.js
api/src/helpers/users.helper.js
api/src/routes/review.Router.js
api/src/routes/user.Router.js

put user terminado

---

api/src/controllers/product.controller.js
client/src/components/assets/NavBar.jsx
client/src/views/footer/footer.css
client/src/views/login/Login.jsx
client/src/views/login/login.css
client/src/views/login/login.less
client/src/views/register/Register.jsx
client/src/views/register/register.css

Agregada imagen en register, estilos en login

arreglos en el login y register

---

api/src/config/app.js
api/src/controllers/market.controller.js
api/src/controllers/reviews.controller.js
api/src/controllers/users.controller.js
api/src/helpers/market.helper.js
api/src/helpers/reviews.helper.js
api/src/helpers/users.helper.js
api/src/routes/market.Router.js

agregue rutas que me buscan todos los market y por id.
cambie de español a ingles las respuestas json que tira la consola al ejecutarse una funcion

Agregue ruta market y cambie las respuestas json a ingles.

---

client/src/App.js
client/src/redux/apiPetitions.js
client/src/redux/slice.js
client/src/views/Card/Card.jsx
client/src/views/detalleProd/Detail.jsx
client/src/views/home/Home.jsx

Peticiones Arregladas

---

api/src/controllers/product.controller.js
api/src/prueba (1).js
client/src/components/filtro/Filtro.jsx
client/src/redux/apiPetitions.js
client/src/redux/slice.js
client/src/views/home/Home.jsx

reempalzo de terry

---

api/src/controllers/users.controller.js
api/src/helpers/users.helper.js
api/src/routes/user.Router.js

verificacion email password

---

api/src/helpers/products.helper.js
api/src/routes/products.Router.js

Category filtrado desde General

Category filtrado desde General

---

api/src/controllers/product.controller.js
api/src/helpers/products.helper.js
api/src/routes/products.Router.js

filtro combinado, Category y Supermarket

filtro combinado, Category y Supermarket

---

api/src/helpers/products.helper.js

Filtros 2.0

---

api/src/helpers/products.helper.js
api/src/routes/products.Router.js
client/src/components/filtro/Filtro.jsx
client/src/components/order/Orden.jsx
client/src/redux/apiPetitions.js
client/src/redux/slice.js

Filtros 95%

---

client/src/views/landing/landing.css
client/src/views/landing/landing.less

arreglado el landing

---

api/src/controllers/product.controller.js
api/src/helpers/users.helper.js

"Enviando archivo Prueba 3"

---

api/src/prueba(3).js
client/src/components/Card/Card.jsx
client/src/components/order/Orden.css
client/src/components/order/Orden.less
client/src/redux/slice.js
client/src/views/detalleProd/Detail.jsx
client/src/views/home/Home.jsx

comparador con prueba 3

---

api/src/routes/user.Router.js
client/src/redux/apiPetitions.js

Cambiando post en api petitions y en ruta de login

login post

---

client/src/components/login/Login.jsx

loin emnsaje correcto

---

client/src/components/detalleComaprar/ComparadorDetail.css
client/src/components/detalleComaprar/ComparadorDetail.jsx
client/src/components/detalleComaprar/ComparadorDetail.less

detail comparador

---

client/src/views/detalleProd/Detail.jsx

arreglado detail

---

api/src/controllers/product.controller.js
api/src/helpers/apiInfo.js
api/src/models/products.js
api/src/routes/products.Router.js

guardando JSON en la propiedad PRICE

guardando JSON en la propiedad PRICE

---

client/src/components/Card/Card.jsx
client/src/components/Navbar/NavBar.jsx
client/src/components/Navbar/navBar.css
client/src/components/login/Login.jsx
client/src/components/register/Register.jsx
client/src/components/user/User.jsx
client/src/redux/apiPetitions.js
client/src/redux/slice.js
client/src/views/detalleProd/Detail.jsx
client/src/views/home/Home.jsx

login y register

---

api/src/prueba(3).js

generador de precios Creado

---

api/src/controllers/users.controller.js
api/src/helpers/createUser.helper.js
api/src/helpers/users.helper.js
api/src/models/users.js
api/src/routes/user.Router.js

hashgoogle añadido y verifica password

hashgoogle añadido y verifica password

---

api/index.js
api/src/prueba(3).js

Le agregué propiedad imagen al generador de precios

agrego imagen a generador de precios

---

client/src/components/login/Login.jsx
client/src/redux/apiPetitions.js
client/src/views/Firebase/GoogleSign.jsx
client/src/views/home/Home.jsx

Login con Google 95%

---

api/src/controllers/product.controller.js
api/src/controllers/users.controller.js
api/src/helpers/products.helper.js
api/src/routes/products.Router.js

get products/name en orden

---

api/src/controllers/mercPago.controller.js
api/src/routes/market.Router.js

Ordene controller y router de mercado pago

Archivos mp

---

api/src/controllers/mercPago.controller.js
api/src/helpers/merPago.helper.js
api/src/routes/market.Router.js
client/src/App.js
client/src/components/Mercadomp.jsx
client/src/redux/apiPetitions/userPetitions.js

Button no funciona nose porque, se rompio mi compu

Button no funciona nose porque

---

client/src/components/login/Login.jsx
client/src/views/landing/Landing.jsx

Poniendome la 10

---

api/src/controllers/mercPago.controller.js
api/src/helpers/merPago.helper.js
api/src/routes/market.Router.js

Back nuevo MP

---

api/src/helpers/products.helper.js
api/src/routes/products.Router.js

filtros integrados "/category/:category/:brand/:order/:name"

filtros integrados "/category/:category/:brand/:order/:name"

---

api/src/helpers/products.helper.js

añadiendo filtro por marca

---

api/index.js
api/src/controllers/product.controller.js
api/src/helpers/products.helper.js
api/src/routes/products.Router.js

"filtros al 100%"

---

api/src/helpers/users.helper.js
client/src/components/filtro/Filtro.jsx
client/src/components/login/Login.jsx
client/src/components/order/Orden.jsx
client/src/redux/apiPetitions/productsPetitions.js
client/src/redux/apiPetitions/userPetitions.js
client/src/views/home/Home.jsx

Filtros funcionan Juan deja de llorar

Filtros funcionan Juan deja de llorar

---

api/src/config/app.js
api/src/controllers/controller.price.js
api/src/helpers/products.helper.js
api/src/models/users.js
api/src/routes/price.router.js

"rutas especiales y no especiales creadas"

"rutas especiales y no especiales creadas"

---

api/src/controllers/market.controller.js
api/src/helpers/market.helper.js
api/src/models/review.js

Agregue el promedio de puntajes en mercados

promedio puntajes en mercados

---

client/src/views/detalleProd/Detail.jsx
client/src/views/detalleProd/detalleProd.css
client/src/views/footer/Footer.jsx
client/src/views/footer/footer.css

Footer cambiada y details funciona, estilos en progreso no se enojen

Footer cambiada y details funciona, estilos en progreso no se enojen

---

api/src/controllers/market.controller.js
api/src/helpers/market.helper.js

Faltaba esto en el market por id.

promedio de puntaje en getMarketById

---

api/.gitignore
api/node_modules/.package-lock.json
api/package-lock.json
api/package.json
api/src/controllers/users.controller.js
api/src/helpers/createUser.helper.js
api/src/helpers/reviews.helper.js
api/src/helpers/users.helper.js
api/src/models/review.js
api/src/models/users.js
api/src/prueba(4).js

userName borrado y Encriptador de contraseñas añadido, recordar instalar la dependencia bcrypt

userName borrado y Encriptador de contraseñas añadido, recordar instalar dependencia bcrypt

---

api/src/controllers/reviews.controller.js

reviews con dadtos del usuario

reviews con dadtos del usuario

---

api/src/controllers/users.controller.js
api/src/helpers/createUser.helper.js
api/src/helpers/helpers.price.js
api/src/helpers/market.helper.js
api/src/helpers/products.helper.js
api/src/helpers/reviews.helper.js
api/src/helpers/users.helper.js
client/src/components/PerfilUser/Comentarios.jsx
client/src/components/PerfilUser/Datos.jsx
client/src/components/PerfilUser/Perfil.css
client/src/components/PerfilUser/PerfilUser.jsx
client/src/components/user/UserPrueba.jsx
client/src/redux/apiPetitions/userPetitions.js

Arreglando Cosas

---

api/index.js
api/src/controllers/mercPago.controller.js
api/src/controllers/product.controller.js
api/src/models/membership.js
api/src/routes/market.Router.js
api/src/routes/price.router.js
api/src/routes/router.price.js

tabla creada, ruta creada y funcion q crea el primer payment en 2350, y el update

tabla creada, ruta creada y funcion q crea el primer payment en 2350, y el update

---

api/index.js
api/src/controllers/users.controller.js
api/src/helpers/users.helper.js

updateUser actualizado, ahora devuelve todos los datos del usuario

updateUser actualizado, ahora devuelve todos los datos del usuario

---

client/src/App.js
client/src/components/PerfilUser/Comentarios.jsx
client/src/components/PerfilUser/Datos.jsx
client/src/components/login/CambiarContra.jsx
client/src/components/login/Login.jsx
client/src/components/register/Register.jsx
client/src/redux/apiPetitions/productsPetitions.js
client/src/redux/apiPetitions/userPetitions.js
client/src/redux/axios.js

Perfil, faltan comentarios(me falta ruta), cambiar contraseña (falta que le llegue al mail la direccion)yo lo puse que lo redirija directo al componente

Perfil, faltan comentarios(me falta ruta), cambiar contraseña

---

client/src/components/Graphics/functionsGraphics.js
client/src/components/Graphics/graphicsDonut.js
client/src/components/Graphics/graphicsLine.js
client/src/components/dashboard/DashUsers.jsx

Faltan crear las funciones de ordenamiento o que devuelva cuantos typeAccount de cada uno hay.

Graficos funcionando, faltan funciones

---

client/src/components/Card/CardM.jsx

no subir de rango a mercader aun unsario q no haya creado su tienda

no subir de rango a mercader aun unsario q no haya creado su tienda

---

api/src/config/db.js
api/src/controllers/market.controller.js
api/src/helpers/market.helper.js
api/src/helpers/reviews.helper.js
api/src/helpers/users.helper.js
api/src/models/review.js
api/src/models/superM.js

borrado de tiendas y comentarios al cambiar la activity del usuario

borrado de tiendas y comentarios al cambiar la activity del usuario

---

api/src/controllers/market.controller.js
api/src/helpers/market.helper.js
api/src/helpers/users.helper.js
api/src/models/superM.js
api/src/routes/price.router.js

solo mostrara la tienda si es tipo de cuenta 2 y añadido la ruta price

solo mostrara la tienda si es tipo de cuenta 2 y añadido la ruta price
